/**
 * SchoolGate API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Machine-readable outcome code present on every envelope (success and error). Clients resolve it against their localization catalogs; the server-side message is only a fallback. Reason codes such as ENROLLMENT_REVIEW_TIMEOUT also appear in notification payloads and rejection reasons.
 */
export const ApiCodeDto = {
    Ok: 'OK',
    AuthRegistered: 'AUTH_REGISTERED',
    AuthLoginSuccess: 'AUTH_LOGIN_SUCCESS',
    PaymentDeclared: 'PAYMENT_DECLARED',
    InvoiceVerified: 'INVOICE_VERIFIED',
    InvoiceInvalid: 'INVOICE_INVALID',
    NotFound: 'NOT_FOUND',
    Unauthorized: 'UNAUTHORIZED',
    InvalidCredentials: 'INVALID_CREDENTIALS',
    Forbidden: 'FORBIDDEN',
    Conflict: 'CONFLICT',
    ValidationFailed: 'VALIDATION_FAILED',
    Unprocessable: 'UNPROCESSABLE',
    NoSeats: 'NO_SEATS',
    InvalidStatus: 'INVALID_STATUS',
    AcademicYearClosed: 'ACADEMIC_YEAR_CLOSED',
    EnrollmentWindowClosed: 'ENROLLMENT_WINDOW_CLOSED',
    RateLimited: 'RATE_LIMITED',
    HttpsRequired: 'HTTPS_REQUIRED',
    ServiceUnavailable: 'SERVICE_UNAVAILABLE',
    InternalError: 'INTERNAL_ERROR',
    EnrollmentReviewTimeout: 'ENROLLMENT_REVIEW_TIMEOUT',
    EnrollmentPaymentTimeout: 'ENROLLMENT_PAYMENT_TIMEOUT',
    EnrollmentPending: 'ENROLLMENT_PENDING',
    EnrollmentAccepted: 'ENROLLMENT_ACCEPTED',
    EnrollmentRejected: 'ENROLLMENT_REJECTED',
    PaymentRequested: 'PAYMENT_REQUESTED',
    PaymentValidated: 'PAYMENT_VALIDATED',
    PaymentRejected: 'PAYMENT_REJECTED',
    PaymentFailed: 'PAYMENT_FAILED'
} as const;
export type ApiCodeDto = typeof ApiCodeDto[keyof typeof ApiCodeDto];

