/**
 * SchoolGate API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MetaDto } from './meta';
import { ApiCodeDto } from './apiCode';
import { ErrorBodyDto } from './errorBody';
import { SchoolRegistrationResultDto } from './schoolRegistrationResult';


export interface AuthSchoolRegistrationsPost201ResponseDto { 
    code?: ApiCodeDto;
    data?: SchoolRegistrationResultDto;
    error?: ErrorBodyDto;
    meta?: MetaDto;
}
export namespace AuthSchoolRegistrationsPost201ResponseDto {
}


