/**
 * SchoolGate API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MetaDto } from './meta';
import { ApiCodeDto } from './apiCode';
import { PasswordResetResultDto } from './passwordResetResult';
import { ErrorBodyDto } from './errorBody';


export interface AuthSchoolUsersIdPasswordPut200ResponseDto { 
    code?: ApiCodeDto;
    data?: PasswordResetResultDto;
    error?: ErrorBodyDto;
    meta?: MetaDto;
}
export namespace AuthSchoolUsersIdPasswordPut200ResponseDto {
}


