/**
 * SchoolGate API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TokenResponseDto } from './tokenResponse';
import { UserDto } from './user';


export interface AuthTokensEnvelopeAllOfDataDto { 
    user?: UserDto;
    tokens?: TokenResponseDto;
    message?: string;
}

