/**
 * SchoolGate API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MetaDto } from './meta';
import { AuthTokensEnvelopeAllOfDataDto } from './authTokensEnvelopeAllOfData';
import { ErrorBodyDto } from './errorBody';


export interface AuthTokensEnvelopeDto { 
    data?: AuthTokensEnvelopeAllOfDataDto;
    error?: ErrorBodyDto;
    meta?: MetaDto;
}

