/**
 * SchoolGate API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ConfirmPasswordResetRequestDto { 
    email: string;
    /**
     * The 6-digit code emailed by POST /auth/password-reset/code.
     */
    code: string;
    new_password: string;
}

