/**
 * SchoolGate API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateSchoolUserRequestDto { 
    email: string;
    password: string;
    first_name: string;
    last_name: string;
    phone?: string;
    role: CreateSchoolUserRequestDto.RoleEnum;
    /**
     * School the staff account is scoped to (required; multi-staff model)
     */
    school_id: number;
}
export namespace CreateSchoolUserRequestDto {
    export const RoleEnum = {
        SchoolAdmin: 'school_admin',
        SchoolEditor: 'school_editor'
    } as const;
    export type RoleEnum = typeof RoleEnum[keyof typeof RoleEnum];
}


