/**
 * SchoolGate API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateEnrollmentRequestDto { 
    school_class_id: number;
    academic_year?: string;
    is_returning_student?: boolean;
}

