/**
 * SchoolGate API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreatePersonRequestDto { 
    first_name: string;
    last_name: string;
    birth_date?: string;
    gender: CreatePersonRequestDto.GenderEnum;
}
export namespace CreatePersonRequestDto {
    export const GenderEnum = {
        Male: 'male',
        Female: 'female'
    } as const;
    export type GenderEnum = typeof GenderEnum[keyof typeof GenderEnum];
}


