/**
 * SchoolGate API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DashboardSummarySchoolClassesInnerDto { 
    school_class_id?: number;
    school_class_name?: string;
    total_seats?: number;
    seats_remaining?: number;
    validated_count?: number;
    seats_filled_percent?: number;
}

