/**
 * SchoolGate API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DashboardSummaryRecentPaymentsInnerDto { 
    id?: number;
    student_name?: string;
    amount_cents?: number;
    status?: string;
    declared_at?: string;
}

