/**
 * SchoolGate API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DashboardSummarySchoolClassesInnerDto } from './dashboardSummarySchoolClassesInner';


export interface DashboardSummaryDto { 
    role?: string;
    pending_payments_count?: number;
    validated_payments_count?: number;
    aggregate_filled_percent?: number;
    school_classes?: Array<DashboardSummarySchoolClassesInnerDto>;
}

