/**
 * SchoolGate API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DeclarePaymentRequestDto { 
    enrollment_id: number;
    type: DeclarePaymentRequestDto.TypeEnum;
    installment_number?: number;
    amount_cents: number;
    mobile_money_reference: string;
}
export namespace DeclarePaymentRequestDto {
    export const TypeEnum = {
        EnrollmentFee: 'enrollment_fee',
        TuitionInstallment: 'tuition_installment'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


