/**
 * SchoolGate API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DeclarePaymentRequestDto { 
    enrollment_id: number;
    type: DeclarePaymentRequestDto.TypeEnum;
    installment_number?: number;
    amount_cents: number;
    payment_method: DeclarePaymentRequestDto.PaymentMethodEnum;
    /**
     * Mobile Money phone number (USSD push target)
     */
    payer_msisdn: string;
}
export namespace DeclarePaymentRequestDto {
    export const TypeEnum = {
        EnrollmentFee: 'enrollment_fee',
        TuitionInstallment: 'tuition_installment'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
    export const PaymentMethodEnum = {
        Mtn: 'mtn',
        Orange: 'orange'
    } as const;
    export type PaymentMethodEnum = typeof PaymentMethodEnum[keyof typeof PaymentMethodEnum];
}


