/**
 * SchoolGate API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DocumentTypeDto } from './documentType';


export interface DocumentRequirementDto { 
    id?: number;
    document_type?: DocumentTypeDto;
    purpose?: DocumentRequirementDto.PurposeEnum;
    required?: boolean;
    other_label?: string;
}
export namespace DocumentRequirementDto {
    export const PurposeEnum = {
        Enrollment: 'enrollment',
        TuitionPayment: 'tuition_payment'
    } as const;
    export type PurposeEnum = typeof PurposeEnum[keyof typeof PurposeEnum];
}


