/**
 * SchoolGate API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DocumentRequirementInputDto } from './documentRequirementInput';


export interface DocumentRequirementsRequestDto { 
    requirements?: Array<DocumentRequirementInputDto>;
}

