/**
 * SchoolGate API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DocumentRequirementDto } from './documentRequirement';
import { MetaDto } from './meta';
import { ApiCodeDto } from './apiCode';
import { ErrorBodyDto } from './errorBody';


export interface DocumentRequirementListEnvelopeDto { 
    code?: ApiCodeDto;
    data?: Array<DocumentRequirementDto>;
    error?: ErrorBodyDto;
    meta?: MetaDto;
}
export namespace DocumentRequirementListEnvelopeDto {
}


