/**
 * SchoolGate API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DocumentTypeDto } from './documentType';


export interface DocumentChecklistItemDto { 
    document_type?: DocumentTypeDto;
    purpose?: DocumentChecklistItemDto.PurposeEnum;
    required?: boolean;
    satisfied?: boolean;
}
export namespace DocumentChecklistItemDto {
    export const PurposeEnum = {
        Enrollment: 'enrollment',
        TuitionPayment: 'tuition_payment'
    } as const;
    export type PurposeEnum = typeof PurposeEnum[keyof typeof PurposeEnum];
}


