/**
 * SchoolGate API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MetaDto } from './meta';
import { ApiCodeDto } from './apiCode';
import { DocumentChecklistItemDto } from './documentChecklistItem';
import { ErrorBodyDto } from './errorBody';


export interface DocumentChecklistEnvelopeDto { 
    code?: ApiCodeDto;
    data?: Array<DocumentChecklistItemDto>;
    error?: ErrorBodyDto;
    meta?: MetaDto;
}
export namespace DocumentChecklistEnvelopeDto {
}


