/**
 * SchoolGate API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DocumentRequirementInputDto { 
    document_type_id: number;
    purpose: DocumentRequirementInputDto.PurposeEnum;
    required?: boolean;
    other_label?: string;
}
export namespace DocumentRequirementInputDto {
    export const PurposeEnum = {
        Enrollment: 'enrollment',
        TuitionPayment: 'tuition_payment'
    } as const;
    export type PurposeEnum = typeof PurposeEnum[keyof typeof PurposeEnum];
}


