/**
 * SchoolGate API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DocumentDto { 
    id?: number;
    filename?: string;
    content_type?: string;
    size_bytes?: number;
    created_at?: string;
}

