/**
 * SchoolGate API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MetaDto } from './meta';
import { ApiCodeDto } from './apiCode';
import { ErrorBodyDto } from './errorBody';
import { DocumentTypeDto } from './documentType';


export interface DocumentTypeListEnvelopeDto { 
    code?: ApiCodeDto;
    data?: Array<DocumentTypeDto>;
    error?: ErrorBodyDto;
    meta?: MetaDto;
}
export namespace DocumentTypeListEnvelopeDto {
}


