/**
 * SchoolGate API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Set on listings. Paid counts validated payments only; pending ones await the operator and do not reduce what remains. Tuition is every installment of the class; the enrollment fee is reported apart.
 */
export interface EnrollmentBalanceDto { 
    tuition_total_cents?: number;
    tuition_paid_cents?: number;
    tuition_pending_cents?: number;
    tuition_remaining_cents?: number;
    tuition_settled?: boolean;
    enrollment_fee_cents?: number;
    enrollment_fee_paid_cents?: number;
    enrollment_fee_status?: EnrollmentBalanceDto.EnrollmentFeeStatusEnum;
}
export namespace EnrollmentBalanceDto {
    export const EnrollmentFeeStatusEnum = {
        Paid: 'paid',
        Partial: 'partial',
        Pending: 'pending',
        Unpaid: 'unpaid'
    } as const;
    export type EnrollmentFeeStatusEnum = typeof EnrollmentFeeStatusEnum[keyof typeof EnrollmentFeeStatusEnum];
}


