/**
 * SchoolGate API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SchoolClassDto } from './schoolClass';
import { SchoolDto } from './school';


export interface EnrollmentDto { 
    id?: number;
    parent_id?: number;
    school_class_id?: number;
    academic_year?: string;
    status?: string;
    is_returning_student?: boolean;
    requires_documents?: boolean;
    payment_validated?: boolean;
    rejection_reason?: string;
    created_at?: string;
    school_class?: SchoolClassDto;
    school?: SchoolDto;
}

