/**
 * SchoolGate API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MetaDto } from './meta';
import { ApiCodeDto } from './apiCode';
import { DocumentDto } from './document';
import { ErrorBodyDto } from './errorBody';


export interface EnrollmentsIdDocumentsPost201ResponseDto { 
    code?: ApiCodeDto;
    data?: Array<DocumentDto>;
    error?: ErrorBodyDto;
    meta?: MetaDto;
}
export namespace EnrollmentsIdDocumentsPost201ResponseDto {
}


