/**
 * SchoolGate API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiCodeDto } from './apiCode';


export interface ErrorBodyDto { 
    code?: ApiCodeDto;
    message?: string;
}
export namespace ErrorBodyDto {
}


