/**
 * SchoolGate API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InstallmentRequestDto { 
    number: number;
    amount_cents: number;
    due_date: string;
    advance_allowed?: boolean;
    /**
     * Required > 0 when advance_allowed is true
     */
    advance_percentage?: number;
}

