/**
 * SchoolGate API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InstallmentDto { 
    id?: number;
    number?: number;
    amount_cents?: number;
    due_date?: string;
    advance_allowed?: boolean;
    advance_percentage?: number;
}

