/**
 * SchoolGate API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InvoiceDto { 
    id?: string;
    payment_id?: number;
    signature_hash?: string;
    issued_at?: string;
    amount_cents?: number;
    school_name?: string;
    school_address?: string;
    school_class_name?: string;
    parent_name?: string;
    parent_email?: string;
    payment_type?: string;
    installment_number?: number;
    mobile_reference?: string;
}

