/**
 * SchoolGate API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InvoiceDto } from './invoice';


export interface InvoiceVerifyEnvelopeAllOfDataDto { 
    valid?: boolean;
    invoice?: InvoiceDto;
    message?: string;
}

