/**
 * SchoolGate API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InvoiceVerifyEnvelopeAllOfDataDto } from './invoiceVerifyEnvelopeAllOfData';
import { MetaDto } from './meta';
import { ErrorBodyDto } from './errorBody';


export interface InvoiceVerifyEnvelopeDto { 
    data?: InvoiceVerifyEnvelopeAllOfDataDto;
    error?: ErrorBodyDto;
    meta?: MetaDto;
}

