/**
 * SchoolGate API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MetaDto } from './meta';
import { InvoiceDto } from './invoice';
import { ApiCodeDto } from './apiCode';
import { ErrorBodyDto } from './errorBody';


export interface InvoiceListEnvelopeDto { 
    code?: ApiCodeDto;
    data?: Array<InvoiceDto>;
    error?: ErrorBodyDto;
    meta?: MetaDto;
}
export namespace InvoiceListEnvelopeDto {
}


