/**
 * SchoolGate API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MatriculeVerificationConfigRequestDto { 
    allow_direct_payment_for_returning_students?: boolean;
    mode?: MatriculeVerificationConfigRequestDto.ModeEnum;
    /**
     * Required when mode is \"api\".
     */
    api_url?: string;
    /**
     * Write-only (never echoed back by GET/PUT school responses). This endpoint always replaces all four fields together, so resend the existing key when only toggling mode or the allow flag.
     */
    api_key?: string;
}
export namespace MatriculeVerificationConfigRequestDto {
    export const ModeEnum = {
        None: 'none',
        File: 'file',
        Api: 'api'
    } as const;
    export type ModeEnum = typeof ModeEnum[keyof typeof ModeEnum];
}


