/**
 * SchoolGate API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MetaDto } from './meta';
import { NotificationDto } from './notification';
import { ApiCodeDto } from './apiCode';
import { ErrorBodyDto } from './errorBody';


export interface NotificationListEnvelopeDto { 
    code?: ApiCodeDto;
    data?: Array<NotificationDto>;
    error?: ErrorBodyDto;
    meta?: MetaDto;
}
export namespace NotificationListEnvelopeDto {
}


