/**
 * SchoolGate API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface NotificationDto { 
    id?: number;
    type?: string;
    title?: string;
    body?: string;
    read?: boolean;
    created_at?: string;
}

