/**
 * SchoolGate API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PasswordResetResultDto { 
    /**
     * How many pending reset requests of the user this closed.
     */
    resolved_requests?: number;
}

