/**
 * SchoolGate API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MetaDto } from './meta';
import { ApiCodeDto } from './apiCode';
import { ErrorBodyDto } from './errorBody';
import { PasswordResetRequestRecordDto } from './passwordResetRequestRecord';


export interface PasswordResetRequestRecordListEnvelopeDto { 
    code?: ApiCodeDto;
    data?: Array<PasswordResetRequestRecordDto>;
    error?: ErrorBodyDto;
    meta?: MetaDto;
}
export namespace PasswordResetRequestRecordListEnvelopeDto {
}


