/**
 * SchoolGate API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserDto } from './user';


export interface PasswordResetRequestRecordDto { 
    id?: number;
    user_id?: number;
    user?: UserDto;
    status?: PasswordResetRequestRecordDto.StatusEnum;
    requested_at?: string;
    resolved_at?: string;
    /**
     * The admin who set the new password.
     */
    resolved_by?: number;
}
export namespace PasswordResetRequestRecordDto {
    export const StatusEnum = {
        Pending: 'pending',
        Resolved: 'resolved'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


