/**
 * SchoolGate API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PaymentSettingsDto { 
    /**
     * True when parents are charged into the school\'s own operator account (COLLECTION_MODE=live), so each enabled Mobile Money channel needs the school\'s API credentials. False with an aggregator charging the platform\'s account: schools enter none.
     */
    merchant_credentials_required?: boolean;
    orange_money_enabled?: boolean;
    orange_money_number?: string;
    orange_money_account_name?: string;
    orange_client_id?: string;
    /**
     * Client secret, X-AUTH-TOKEN and PIN are saved (never returned).
     */
    orange_secrets_set?: boolean;
    mtn_momo_enabled?: boolean;
    mtn_momo_number?: string;
    mtn_momo_account_name?: string;
    mtn_api_user?: string;
    /**
     * API key and subscription key are saved (never returned).
     */
    mtn_secrets_set?: boolean;
    paypal_enabled?: boolean;
    paypal_email?: string;
    bank_transfer_enabled?: boolean;
    bank_name?: string;
    bank_account_holder?: string;
    /**
     * RIB (23 digits) or IBAN, stored without spaces.
     */
    bank_account_number?: string;
    bank_swift_code?: string;
    /**
     * Absent until the school saves its settings once.
     */
    updated_at?: string;
}

