/**
 * SchoolGate API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SchoolClassDto } from './schoolClass';
import { PersonDto } from './person';
import { SchoolDto } from './school';


export interface PaymentDto { 
    id?: number;
    enrollment_id?: number;
    type?: string;
    installment_number?: number;
    /**
     * Owed to the school.
     */
    amount_cents?: number;
    /**
     * Platform service fee paid by the parent on top of amount_cents.
     */
    fee_cents?: number;
    /**
     * What the operator charges the parent (amount_cents + fee_cents).
     */
    total_cents?: number;
    status?: string;
    payment_method?: string;
    mobile_money_reference?: string;
    payer_msisdn?: string;
    external_reference?: string;
    declared_at?: string;
    validation_deadline?: string;
    validated_at?: string;
    rejected_at?: string;
    rejection_reason?: string;
    person?: PersonDto;
    school?: SchoolDto;
    school_class?: SchoolClassDto;
}

