/**
 * SchoolGate API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PaymentDto { 
    id?: number;
    enrollment_id?: number;
    type?: string;
    installment_number?: number;
    amount_cents?: number;
    status?: string;
    mobile_money_reference?: string;
    declared_at?: string;
    validation_deadline?: string;
    validated_at?: string;
    rejected_at?: string;
}

