/**
 * SchoolGate API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PaymentSettingsRequestDto { 
    orange_money_enabled?: boolean;
    orange_money_number?: string;
    orange_money_account_name?: string;
    /**
     * Orange merchant API OAuth client id.
     */
    orange_client_id?: string;
    /**
     * Write-only. Empty keeps the saved value.
     */
    orange_client_secret?: string;
    /**
     * Write-only X-AUTH-TOKEN issued by Orange. Empty keeps the saved value.
     */
    orange_auth_token?: string;
    /**
     * Write-only merchant channel PIN (4-8 digits). Empty keeps the saved value.
     */
    orange_pin?: string;
    mtn_momo_enabled?: boolean;
    mtn_momo_number?: string;
    mtn_momo_account_name?: string;
    /**
     * MTN MoMo Collection API user (UUID).
     */
    mtn_api_user?: string;
    /**
     * Write-only. Empty keeps the saved value.
     */
    mtn_api_key?: string;
    /**
     * Write-only Collection product subscription key. Empty keeps the saved value.
     */
    mtn_subscription_key?: string;
    paypal_enabled?: boolean;
    paypal_email?: string;
    bank_transfer_enabled?: boolean;
    bank_name?: string;
    bank_account_holder?: string;
    /**
     * RIB (23 digits) or IBAN, stored without spaces.
     */
    bank_account_number?: string;
    bank_swift_code?: string;
}

