/**
 * SchoolGate API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MetaDto } from './meta';
import { ErrorBodyDto } from './errorBody';
import { PaymentDto } from './payment';


export interface PaymentListEnvelopeDto { 
    data?: Array<PaymentDto>;
    error?: ErrorBodyDto;
    meta?: MetaDto;
}

