/**
 * SchoolGate API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MetaDto } from './meta';
import { PaymentsFeePolicyGet200ResponseAllOfDataDto } from './paymentsFeePolicyGet200ResponseAllOfData';
import { ApiCodeDto } from './apiCode';
import { ErrorBodyDto } from './errorBody';


export interface PaymentsFeePolicyGet200ResponseDto { 
    code?: ApiCodeDto;
    data?: PaymentsFeePolicyGet200ResponseAllOfDataDto;
    error?: ErrorBodyDto;
    meta?: MetaDto;
}
export namespace PaymentsFeePolicyGet200ResponseDto {
}


