/**
 * SchoolGate API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MetaDto } from './meta';
import { ApiCodeDto } from './apiCode';
import { PaymentSettingsDto } from './paymentSettings';
import { ErrorBodyDto } from './errorBody';


export interface PaymentSettingsEnvelopeDto { 
    code?: ApiCodeDto;
    data?: PaymentSettingsDto;
    error?: ErrorBodyDto;
    meta?: MetaDto;
}
export namespace PaymentSettingsEnvelopeDto {
}


