/**
 * SchoolGate API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MetaDto } from './meta';
import { ApiCodeDto } from './apiCode';
import { PersonDto } from './person';
import { ErrorBodyDto } from './errorBody';


export interface PersonListEnvelopeDto { 
    code?: ApiCodeDto;
    data?: Array<PersonDto>;
    error?: ErrorBodyDto;
    meta?: MetaDto;
}
export namespace PersonListEnvelopeDto {
}


