/**
 * SchoolGate API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PersonDto { 
    id?: number;
    first_name?: string;
    last_name?: string;
    birth_date?: string;
    /**
     * Omitted only for persons saved before it was collected.
     */
    gender?: PersonDto.GenderEnum;
    /**
     * Immutable student identifier assigned at first enrollment acceptance
     */
    matricule?: string | null;
}
export namespace PersonDto {
    export const GenderEnum = {
        Male: 'male',
        Female: 'female'
    } as const;
    export type GenderEnum = typeof GenderEnum[keyof typeof GenderEnum];
}


