/**
 * SchoolGate API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PersonDto { 
    id?: number;
    first_name?: string;
    last_name?: string;
    birth_date?: string;
    /**
     * Immutable student identifier assigned at first enrollment acceptance
     */
    matricule?: string | null;
}

