/**
 * SchoolGate API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RefreshRequestDto { 
    /**
     * Native-client alternative to the HttpOnly cookie.
     */
    refresh_token?: string;
}

