/**
 * SchoolGate API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RegisterDeviceRequestDto { 
    /**
     * FCM registration token or Firebase installation ID
     */
    registration_id: string;
    kind?: RegisterDeviceRequestDto.KindEnum;
    platform?: RegisterDeviceRequestDto.PlatformEnum;
    app_version?: string;
}
export namespace RegisterDeviceRequestDto {
    export const KindEnum = {
        FcmToken: 'fcm_token',
        Fid: 'fid'
    } as const;
    export type KindEnum = typeof KindEnum[keyof typeof KindEnum];
    export const PlatformEnum = {
        Android: 'android',
        Ios: 'ios',
        Web: 'web'
    } as const;
    export type PlatformEnum = typeof PlatformEnum[keyof typeof PlatformEnum];
}


