/**
 * SchoolGate API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RegisterRequestDto { 
    email: string;
    password: string;
    first_name: string;
    last_name: string;
    phone?: string;
}

