/**
 * SchoolGate API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LevelDto } from './level';
import { SpecialtyDto } from './specialty';
import { InstallmentDto } from './installment';


export interface SchoolClassDto { 
    id?: number;
    school_id?: number;
    education_type?: string;
    pedagogic_system?: string;
    effective_system?: string;
    level?: LevelDto;
    specialty?: SpecialtyDto;
    enrollment_fee_cents?: number;
    installments?: Array<InstallmentDto>;
    total_seats?: number;
    seats_remaining?: number;
    advance_allowed?: boolean;
    advance_percentage?: number;
}

