/**
 * SchoolGate API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SchoolClassDto } from './schoolClass';
import { CityRefDto } from './cityRef';


export interface SchoolDto { 
    id?: number;
    name?: string;
    city_id?: number;
    city?: CityRefDto;
    address?: string;
    phone?: string;
    email?: string;
    status?: string;
    system?: string;
    /**
     * Current academic year derived from the school calendar (Sep–Aug)
     */
    academic_year?: string;
    review_deadline_days?: number;
    payment_deadline_days?: number;
    enrollment_deadline?: string | null;
    school_classes?: Array<SchoolClassDto>;
}

