/**
 * SchoolGate API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InstallmentRequestDto } from './installmentRequest';


export interface SchoolClassRequestDto { 
    level_id: number;
    /**
     * Required when level_id points to reference code `other`
     */
    level_other_label?: string;
    education_type: SchoolClassRequestDto.EducationTypeEnum;
    /**
     * Required when school.system is bilingual
     */
    pedagogic_system?: SchoolClassRequestDto.PedagogicSystemEnum;
    /**
     * Required for technical/vocational; must be null for general
     */
    specialty_id?: number;
    /**
     * Required when specialty_id points to reference code `other`
     */
    specialty_other_label?: string;
    enrollment_fee_cents: number;
    installments?: Array<InstallmentRequestDto>;
    total_seats: number;
    advance_allowed?: boolean;
    advance_percentage?: number;
}
export namespace SchoolClassRequestDto {
    export const EducationTypeEnum = {
        General: 'general',
        Technical: 'technical',
        Vocational: 'vocational'
    } as const;
    export type EducationTypeEnum = typeof EducationTypeEnum[keyof typeof EducationTypeEnum];
    export const PedagogicSystemEnum = {
        Francophone: 'francophone',
        Anglophone: 'anglophone'
    } as const;
    export type PedagogicSystemEnum = typeof PedagogicSystemEnum[keyof typeof PedagogicSystemEnum];
}


