/**
 * SchoolGate API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SchoolRegistrationResultDto { 
    school_id?: number;
    /**
     * active = published now; pending = waiting for an admin.
     */
    status?: SchoolRegistrationResultDto.StatusEnum;
    admin_email?: string;
}
export namespace SchoolRegistrationResultDto {
    export const StatusEnum = {
        Active: 'active',
        Pending: 'pending'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


