/**
 * SchoolGate API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SchoolsIdPaymentMethodsGet200ResponseAllOfDataDto { 
    methods?: Array<SchoolsIdPaymentMethodsGet200ResponseAllOfDataDto.MethodsEnum>;
}
export namespace SchoolsIdPaymentMethodsGet200ResponseAllOfDataDto {
    export const MethodsEnum = {
        Mtn: 'mtn',
        Orange: 'orange'
    } as const;
    export type MethodsEnum = typeof MethodsEnum[keyof typeof MethodsEnum];
}


