/**
 * SchoolGate API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The person who registers the school; becomes its school_admin.
 */
export interface SchoolRegistrationRequestAdminDto { 
    first_name: string;
    last_name: string;
    email: string;
    phone?: string;
    password: string;
}

