/**
 * SchoolGate API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MetaDto } from './meta';
import { SchoolClassDto } from './schoolClass';
import { ApiCodeDto } from './apiCode';
import { ErrorBodyDto } from './errorBody';


export interface SchoolsIdSchoolClassesPost201ResponseDto { 
    code?: ApiCodeDto;
    data?: SchoolClassDto;
    error?: ErrorBodyDto;
    meta?: MetaDto;
}
export namespace SchoolsIdSchoolClassesPost201ResponseDto {
}


