/**
 * SchoolGate API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MetaDto } from './meta';
import { ApiCodeDto } from './apiCode';
import { SchoolsIdPaymentMethodsGet200ResponseAllOfDataDto } from './schoolsIdPaymentMethodsGet200ResponseAllOfData';
import { ErrorBodyDto } from './errorBody';


export interface SchoolsIdPaymentMethodsGet200ResponseDto { 
    code?: ApiCodeDto;
    data?: SchoolsIdPaymentMethodsGet200ResponseAllOfDataDto;
    error?: ErrorBodyDto;
    meta?: MetaDto;
}
export namespace SchoolsIdPaymentMethodsGet200ResponseDto {
}


