/**
 * SchoolGate API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MetaDto } from './meta';
import { ApiCodeDto } from './apiCode';
import { DashboardSummaryDto } from './dashboardSummary';
import { ErrorBodyDto } from './errorBody';


export interface SchoolsIdDashboardGet200ResponseDto { 
    code?: ApiCodeDto;
    data?: DashboardSummaryDto;
    error?: ErrorBodyDto;
    meta?: MetaDto;
}
export namespace SchoolsIdDashboardGet200ResponseDto {
}


