/**
 * SchoolGate API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MetaDto } from './meta';
import { ErrorBodyDto } from './errorBody';
import { SchoolDto } from './school';


export interface SchoolsPost201ResponseDto { 
    data?: SchoolDto;
    error?: ErrorBodyDto;
    meta?: MetaDto;
}

