/**
 * SchoolGate API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SchoolRegistrationRequestSchoolDto { 
    name: string;
    city_id: number;
    system?: SchoolRegistrationRequestSchoolDto.SystemEnum;
    address?: string;
    phone?: string;
    email?: string;
}
export namespace SchoolRegistrationRequestSchoolDto {
    export const SystemEnum = {
        Francophone: 'francophone',
        Anglophone: 'anglophone',
        Bilingual: 'bilingual'
    } as const;
    export type SystemEnum = typeof SystemEnum[keyof typeof SystemEnum];
}


