/**
 * SchoolGate API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MetaDto } from './meta';
import { SchoolsIdDelete200ResponseAllOfDataDto } from './schoolsIdDelete200ResponseAllOfData';
import { ErrorBodyDto } from './errorBody';


export interface SchoolsIdDelete200ResponseDto { 
    data?: SchoolsIdDelete200ResponseAllOfDataDto;
    error?: ErrorBodyDto;
    meta?: MetaDto;
}

