/**
 * SchoolGate API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SchoolRequestDto { 
    name: string;
    city_id: number;
    address?: string;
    phone?: string;
    email?: string;
    status?: SchoolRequestDto.StatusEnum;
    system?: SchoolRequestDto.SystemEnum;
}
export namespace SchoolRequestDto {
    export const StatusEnum = {
        Active: 'active',
        Inactive: 'inactive'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
    export const SystemEnum = {
        Francophone: 'francophone',
        Anglophone: 'anglophone',
        Bilingual: 'bilingual'
    } as const;
    export type SystemEnum = typeof SystemEnum[keyof typeof SystemEnum];
}


