/**
 * SchoolGate API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MetaDto } from './meta';
import { ApiCodeDto } from './apiCode';
import { ErrorBodyDto } from './errorBody';
import { SpecialtyRefDto } from './specialtyRef';


export interface SpecialtyRefListEnvelopeDto { 
    code?: ApiCodeDto;
    data?: Array<SpecialtyRefDto>;
    error?: ErrorBodyDto;
    meta?: MetaDto;
}
export namespace SpecialtyRefListEnvelopeDto {
}


