/**
 * SchoolGate API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TokenResponseDto { 
    access_token?: string;
    expires_in?: number;
    /**
     * Present only when request includes X-Client-Type native.
     */
    refresh_token?: string;
}

