/**
 * SchoolGate API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MetaDto } from './meta';
import { ApiCodeDto } from './apiCode';
import { UserDto } from './user';
import { ErrorBodyDto } from './errorBody';


export interface UserListEnvelopeDto { 
    code?: ApiCodeDto;
    data?: Array<UserDto>;
    error?: ErrorBodyDto;
    meta?: MetaDto;
}
export namespace UserListEnvelopeDto {
}


