/**
 * SchoolGate API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserDto { 
    id?: number;
    email?: string;
    first_name?: string;
    last_name?: string;
    phone?: string;
    role?: UserDto.RoleEnum;
    /**
     * Present only for school_admin/school_editor (multi-staff scoping)
     */
    school_id?: number;
}
export namespace UserDto {
    export const RoleEnum = {
        Admin: 'admin',
        SchoolAdmin: 'school_admin',
        SchoolEditor: 'school_editor',
        Parent: 'parent'
    } as const;
    export type RoleEnum = typeof RoleEnum[keyof typeof RoleEnum];
}


